### ISSUE TITLE
Deleting Node Group Causes Fugio To Crash.

### ISSUE THREAD

**Issue by braedenf** [bigfug/Fugio#10]
Iv'e noticed whenever I try to delete a nodes that have been grouped. When I try to delete the group node Fugio crashes every time. When I go into the group and try to delete the nodes in a group I get the error message "Can't delete the following nodes because they have pins being used by there parent group:"  If I just ungroup the nodes I can then delete them. 

Thanks,
Braeden

**Comment by bigfug** [comment]
After a lot of work, think I've finally cleared all the cut/copy/delete/paste code up.  Still a little work to do on ungrouping selected items, but I'll look at that another time.
