### ISSUE TITLE
crash on replacing end nodes

### ISSUE THREAD

**Issue by one5tone** [bigfug/Fugio#12]
Hello Alex,

Thanks once again for all the hard work you've put into making and releasing Fugio.

I noticed some inconsistent behaviour while replacing the Window (OpenGL) node with a new one but when I tested replacing end-nodes (not sure if that's the proper way of addressing but with that I mean the last node in the chain or chains of a patch) in another example patch and reconnecting the new same end-node, Fugio crashed.

Maybe this is by design & my workflow assumption wrong.

**Comment by bigfug** [comment]
I'm closing this issue as I was unable to replicate this behaviour on recent builds
