### ISSUE TITLE
PortMidi Nodes crashing Fugio on OSX

### ISSUE THREAD

**Issue by braedenf** [bigfug/Fugio#16]
Hey Alex,

Whenever I try to create a PortMidi node Fugio crashes every time. I have installed PortMidi via brew. This didn't happen when the PortMidi library was added to Fugio. I hope this isn't a difficult fix. I'll restart my system and see if it still occurs. 

Cheers,
Braeden

**Comment by braedenf** [comment]
Restarted my Mac and Fugio continues to crash when I create a PortMidi node.

**Comment by bigfug** [comment]
Is this an input/output or other node?  In the start up log, can you copy and paste the list of midi devices it prints out?

**Comment by braedenf** [comment]
So weirdly it's not crashing anymore. I don't have log for when it was crashing but here it is: Initialising plugin PortMidiPlugin
0 "CoreMIDI" "Launch Control" 1 0
1 "CoreMIDI" "Launch Control" 0 1

**Comment by bigfug** [comment]
OK, so not so much to go on there.  Shall we close this issue for now?
