### ISSUE TITLE
No OpenGL output on OSX 10.9.5

### ISSUE THREAD

**Issue by gavspav** [bigfug/Fugio#17]
Just installed Fugio and I can't get any of the OpenGL stuff to work.
I have a late 2011 MBP with a Radeon HD 6750M

I get this message in the logger:
Unknown NodeControlInterface QUuid("{f22866c1-58c7-4c5f-8fb5-28465d93afc5}")
QCocoaGLContext: Falling back to unshared context.
GL_VENDOR "ATI Technologies Inc."
GL_RENDERER "AMD Radeon HD 6750M OpenGL Engine"
GL_VERSION "4.1 ATI-1.24.39"
Profile: Core
Samples: 4
Alpha: -1
Depth: 24
RGB: 8 8 8
Deferred: ("Draw", "Shader Compiler")

**Comment by bigfug** [comment]
OpenGL is fine, this error is because you haven't installed Lua.  In the Fugio application directory you'll find a script called brew_install_update - run that and you should be good! :)

**Comment by gavspav** [comment]
I did try to install lua but I got some errors which I thought were cos it
was already installed. Ill post them when I get back the my computer

On 19 Sep 2016 12:11, "Alex May" <notifications@github.com> wrote:

OpenGL is fine, this error is because you haven't installed Lua. In the
Fugio application directory you'll find a script called brew_install_update
- run that and you should be good! :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bigfug/Fugio/issues/17#issuecomment-247966060>, or mute
the thread

**Comment by bigfug** [comment]
Closing this as no further information was received and it's probably all out of date now anyway! :)
