### ISSUE TITLE
No output in OpenCV and Video Capture.

### ISSUE THREAD

**Issue by rompea** [bigfug/Fugio#18]
Hi Alex. I was testing these new additions of Fugio and none of them gives me a way out. The Video Capture module recognizes my webcam (GeniusFaceCam 315), but does not turn it on.
Also, when I loaded these examples and then quit the program, I get a message "Fugio.exe stopped working".
I appreciate your guidance.

Robinson

**Comment by bigfug** [comment]
What video formats are listed in the Video Capture node?

**Comment by rompea** [comment]
640x480 @ 30 fps (MJPEG) is the one I had taken by default. I just tried YUYV422 and now it works. Thank you for the (indirect) guidance.
