### ISSUE TITLE
missing lua plugin

### ISSUE THREAD

**Issue by micrem73** [bigfug/Fugio#2]
I downloaded the compiled version form Fugio website, disinstalxled old version via maintenance app and installed the new one. 
I open a lua example, and the lua patch has a red dot.
Lua patch is missing if i look for it in nodes selector.

**Comment by bigfug** [comment]
Are you on OS X?

If so, you have to install Lua before you can use the plugin.  See http://wiki.bigfug.com/Lua

**Comment by micrem73** [comment]
On OSX.
Ok, thanks.
