### ISSUE TITLE
install script doesn't install

### ISSUE THREAD

**Issue by micrem73** [bigfug/Fugio#20]
Hi,

i ran the install script, but I can0t find any Fugio app installed then.

Here is log:

Last login: Tue Mar 21 11:47:23 on console
nerd2:~ mic$ /Users/mic/Downloads/install_fugio ; exit;
FFFFFFFFFFFFFFFFFFFFFF                                        iiii
F::::::::::::::::::::F                                       i::::i
F::::::::::::::::::::F                                        iiii
FF::::::FFFFFFFFF::::F
  F:::::F       FFFFFFuuuuuu    uuuuuu     ggggggggg   gggggiiiiiii    ooooooooooo
  F:::::F             u::::u    u::::u    g:::::::::ggg::::gi:::::i  oo:::::::::::oo
  F::::::FFFFFFFFFF   u::::u    u::::u   g:::::::::::::::::g i::::i o:::::::::::::::o
  F:::::::::::::::F   u::::u    u::::u  g::::::ggggg::::::gg i::::i o:::::ooooo:::::o
  F:::::::::::::::F   u::::u    u::::u  g:::::g     g:::::g  i::::i o::::o     o::::o
  F::::::FFFFFFFFFF   u::::u    u::::u  g:::::g     g:::::g  i::::i o::::o     o::::o
  F:::::F             u::::u    u::::u  g:::::g     g:::::g  i::::i o::::o     o::::o
  F:::::F             u:::::uuuu:::::u  g::::::g    g:::::g  i::::i o::::o     o::::o
FF:::::::FF           u:::::::::::::::uug:::::::ggggg:::::g i::::::io:::::ooooo:::::o
F::::::::FF            u:::::::::::::::u g::::::::::::::::g i::::::io:::::::::::::::o
F::::::::FF             uu::::::::uu:::u  gg::::::::::::::g i::::::i oo:::::::::::oo
FFFFFFFFFFF               uuuuuuuu  uuuu    gggggggg::::::g iiiiiiii   ooooooooooo
                                                    g:::::g
                                        gggggg      g:::::g
                                        g:::::gg   gg:::::g
                                         g::::::ggg:::::::g
                                          gg:::::::::::::g
                                             ggg::::::ggg
                                                gggggg
Do you wish to install Fugio? (Y/N) y
ffmpeg is already installed...
Error: Unknown command: cask
==> Migrating Homebrew to v0.9.9
remote: Counting objects: 986, done.
remote: Compressing objects: 100% (919/919), done.
remote: Total 986 (delta 179), reused 359 (delta 41), pack-reused 0
Receiving objects: 100% (986/986), 1.15 MiB | 759.00 KiB/s, done.
Resolving deltas: 100% (179/179), completed with 101 local objects.
From https://github.com/Homebrew/brew
 + 5a9e19f...7095b9b master     -> origin/master  (forced update)
HEAD is now at 7095b9b Merge pull request #2348 from MikeMcQuaid/up-to-date-requirement-formulae
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  http://docs.brew.sh/Analytics.html

==> Tapping homebrew/core
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4255, done.
remote: Compressing objects: 100% (4080/4080), done.
remote: Total 4255 (delta 45), reused 441 (delta 23), pack-reused 0
Receiving objects: 100% (4255/4255), 3.40 MiB | 700.00 KiB/s, done.
Resolving deltas: 100% (45/45), done.
Checking connectivity... done.
Tapped 4091 formulae (4,288 files, 10.7MB)
==> Cleaning up /Library/Caches/Homebrew...
Removing: /Library/Caches/Homebrew/fdk-aac-0.1.4.yosemite.bottle.tar.gz... (871.9KB)
Removing: /Library/Caches/Homebrew/ffmpeg-2.6.3.tar.bz2... (7.4MB)
Removing: /Library/Caches/Homebrew/lua-5.2.3_2.yosemite.bottle.1.tar.gz... (203.5KB)
Removing: /Library/Caches/Homebrew/pkg-config-0.28.yosemite.bottle.2.tar.gz... (220.1KB)
Removing: /Library/Caches/Homebrew/sdl-1.2.15.yosemite.bottle.2.tar.gz... (441.6KB)
Removing: /Library/Caches/Homebrew/ssh-copy-id-6.8p1.yosemite.bottle.tar.gz... (104.2KB)
Removing: /Library/Caches/Homebrew/texi2html-1.82.yosemite.bottle.1.tar.gz... (446.0KB)
Removing: /Library/Caches/Homebrew/x264-r2533.yosemite.bottle.tar.gz... (1.3MB)
Removing: /Library/Caches/Homebrew/xvid-1.3.3.yosemite.bottle.2.tar.gz... (482.9KB)
Removing: /Library/Caches/Homebrew/yasm-1.3.0.yosemite.bottle.1.tar.gz... (1.3MB)
==> Migrating /Library/Caches/Homebrew to /Users/mic/Library/Caches/Homebrew...
==> Deleting /Library/Caches/Homebrew...
Warning: Failed to delete /Library/Caches/Homebrew.
Please do so manually.
Already up-to-date.
==> Migrating HOMEBREW_REPOSITORY (please wait)...
==> Migrated HOMEBREW_REPOSITORY to /usr/local/Homebrew!
Homebrew no longer needs to have ownership of /usr/local. If you wish you can
return /usr/local to its default ownership with:
  sudo chown root:wheel /usr/local
Updating Homebrew...
==> Upgrading 8 outdated packages, with result:
fdk-aac 0.1.5, ffmpeg 3.2.4, lua 5.2.4_4, pkg-config 0.29.1_2, ssh-copy-id 7.4p1, texi2html 5.0, x264 r2748, xvid 1.3.4
==> Upgrading fdk-aac 
==> Downloading https://homebrew.bintray.com/bottles/fdk-aac-0.1.5.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring fdk-aac-0.1.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/fdk-aac/0.1.5: 14 files, 1.8MB
==> Upgrading ffmpeg --with-fdk-aac --with-sdl2 --with-tools
==> Installing dependencies for ffmpeg: pkg-config, gettext, texi2html, x264, xvid, sdl2
==> Installing ffmpeg dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.1_2.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring pkg-config-0.29.1_2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.1_2: 10 files, 627.5KB
==> Installing ffmpeg dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring gettext-0.19.8.1.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

macOS provides the BSD gettext library and some software gets confused if both are in the library path.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.8.1: 1,934 files, 17.0MB
==> Installing ffmpeg dependency: texi2html
==> Downloading https://homebrew.bintray.com/bottles/texi2html-5.0.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring texi2html-5.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/texi2html/5.0: 278 files, 6.2MB
==> Installing ffmpeg dependency: x264
==> Downloading https://homebrew.bintray.com/bottles/x264-r2748.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring x264-r2748.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/x264/r2748: 11 files, 3.3MB
==> Installing ffmpeg dependency: xvid
==> Downloading https://homebrew.bintray.com/bottles/xvid-1.3.4.yosemite.bottle.tar.gz
######################################################################## 100,0%
==> Pouring xvid-1.3.4.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/xvid/1.3.4: 9 files, 1.3MB
==> Installing ffmpeg dependency: sdl2
==> Downloading https://homebrew.bintray.com/bottles/sdl2-2.0.5.yosemite.bottle.1.tar.gz
######################################################################## 100,0%
==> Pouring sdl2-2.0.5.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/sdl2/2.0.5: 84 files, 3.9MB
==> Installing ffmpeg --with-fdk-aac --with-sdl2 --with-tools
==> Using the sandbox
==> Downloading https://ffmpeg.org/releases/ffmpeg-3.2.4.tar.bz2
######################################################################## 100,0%
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/3.2.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --ena
==> make install
==> make alltools
🍺  /usr/local/Cellar/ffmpeg/3.2.4: 273 files, 53.5MB, built in 3 minutes 7 seconds
==> Upgrading lua 
==> Downloading https://homebrew.bintray.com/bottles/lua-5.2.4_4.yosemite.bottle.1.tar.gz
######################################################################## 100,0%
==> Pouring lua-5.2.4_4.yosemite.bottle.1.tar.gz
==> Caveats
Please be aware due to the way Luarocks is designed any binaries installed
via Luarocks-5.2 AND 5.1 will overwrite each other in /usr/local/bin.

This is, for now, unavoidable. If this is troublesome for you, you can build
rocks with the `--tree=` command to a special, non-conflicting location and
then add that to your `$PATH`.
==> Summary
🍺  /usr/local/Cellar/lua/5.2.4_4: 144 files, 705.5KB
==> Upgrading ssh-copy-id 
==> Downloading https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-7.4p1.tar.gz

curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect
Trying a mirror...
==> Downloading https://www.mirrorservice.org/pub/OpenBSD/OpenSSH/portable/openssh-7.4p1.tar.gz
######################################################################## 100,0%
🍺  /usr/local/Cellar/ssh-copy-id/7.4p1: 8 files, 342.2KB, built in 6 seconds
logout

[Processo completato]

**Comment by micrem73** [comment]
Running again the install script, this time I don0t get the first error anymore and it installs correctly.

**Comment by bigfug** [comment]
I've added the cask tap into the installer script
