### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mrrm92** [bigfug/Fugio#28]
Dear, is Fugio a LADSPA/DSSI and FreeFrame host?

**Comment by bigfug** [comment]
FreeFrame support is in development

I had a look at LADSPA and it's quite old - the compiled plugins for macOS were all 32-bit, which meant they weren't usable in Fugio (64-bit only on macOS).

Wouldn't LV2 be a better choice?

**Comment by mrrm92** [comment]
As far as it's open, yes

Il 03 Feb 2018 11:52, "Alex May" <notifications@github.com> ha scritto:

**Comment by mrrm92** [comment]
Yes, LV2 is open and would be nice to have in Fugio.
Is FFGL supported yet?
