### ISSUE TITLE
maintenancetool bug

### ISSUE THREAD

**Issue by micrem73** [bigfug/Fugio#35]
I run maintenancetool. I chose "update components".
When the process finishes, I run Fugio. 
An error window says it's impossibile to run Fugio.
I run again maintenancetool to delete the app. Then again to install from scratch.
I run Fugio but i get the same error.

**Comment by bigfug** [comment]
I'm moving on from using the maintenancetool in the next version of Fugio so I'm not planning on fixing this.  I'd suggest deleting the Fugio directory and using the latest 3.0.0 version.
