### ISSUE TITLE
UDP Receiver seems broken on WIndows10 - no way to dump network socket information

### ISSUE THREAD

**Issue by kquinsland** [bigfug/Fugio#4]
Hi!

I've recently started playing with Fugio.  I like it.

I am having an issue on a Windows10 with the OSC node receiver.  The issues are twofold:

1. There is no way for me to see raw incoming data or check that the node was able to bind to the socket
2. There is no way to dump the raw messages that are coming through.  I was able to get around this with a simple / free utility that allows me to monitor OSC messages.  http://frieder-weiss.de/OSC/index.html

*The Issue*:
OSC Monitor (linked above) is able to bind to port 6969 on my local machine. Using a free OSC app on my phone, i am able to connect and send data.  I can see the data being logged.

If i then:

1. Close OSC Monitor and open a `fug` file that has a UDP receiver and an OSC decoder
2. Verify that the patch is listening on the same port that the OSC Monitor was listening on
3. press the same buttons / toggle the same sliders in the same order on the android app again

I should expect that i can then "add an output pin" on the decoder and i should be presented with a list of the outputs and addresses that i just saw scrolling by in OSC Monitor.

I do not.

So, this is really a "OSC Decoder does not show list of 'discovered' addresses" issue, but I am un able to debug beyond showing that a 3rd party tool can receive OSC messages on my machine from a wireless device.  I don't know where within the windows networking stack or Fugio the issue lies.

help?

**Comment by bigfug** [comment]
Thanks for the report.  What was the Android OSC app you were using?

**Comment by kquinsland** [comment]
I was using an app called QuickOSC:
https://play.google.com/store/apps/details?id=com.ahmetkizilay.controls.osc


On my windows 10 device i was attempting to use:
http://freshvanroot.com/metroosc/

But i was not seeing any activity from that application with the OSCMonitor device; that's when i decided to introduce another app / platform (QuickOSC on android 6) into the mix.

**Comment by bigfug** [comment]
Investigated OSC issue with QuickOSC app, which seems to be sending malformed OSC messages.  I've added some support but it doesn't completely work as intended.  This can't be fixed further without affecting the proper functionality.

**Comment by kquinsland** [comment]
Thanks for the update.

Can you provide any details about what was making messages malformed?  I'll open a ticket w/ the quickOSC app author or the author of w/e library they're using.

**Comment by bigfug** [comment]
Sure, the messages were of the form:

/but11/1,

Which is meant to set /but11 (button 11) to the value of 1

The correct value should be:

/but11,f 1

Which specifies a single floating point argument, which is 1.  Obviously I've left out the null padding that is required.

The official specification is: http://opensoundcontrol.org/spec-1_0

Also, the buttons should send messages when they're released (setting the value to zero)
