### ISSUE TITLE
Problem with nodes and Windows 

### ISSUE THREAD

**Issue by braedenf** [bigfug/Fugio#5]
I posted this to Alex earlier on Facebook, but I'll post the conversation here so all can see.

Braeden: Hey Alex, hope all the Fugio dev is going well! I've noticed an issue on Osx with nodes and windows. When I resize a window, a node box will sometimes draw over the other windows. Thought I should let you know, just in case you are unaware of this issue. Thanks.

Alex: I've noticed it too. Almost certain it's started happening when I upgraded Qt (the framework Fugio is built on) to 5.7. Probably should have waited 🙂. Depending on how long it'll be for their fix, I might roll back to 5.6 for a bit. Thanks for letting me know.

Braeden: Ah right, it's only a minor problem really. If I resize the other windows it seems to fix it. But just popping out the text editor works best. Ohh I was wondering if it is at all possible to have an option of opening multiple Patches (self-contained) at once, or have the ability to tab between patches easily? It's tricky when I have one of your examples to reference while I'm doing my own patch. Hope that makes sense haha.

Alex: Of course - those are good suggestions!  If you don't mind, it'd be great if you could add issues and ideas onto the issue tracker.  It gets really difficult to keep track of lots of messages on lots of different social media platforms,  also it lets other people see them and suggest things too: https://github.com/bigfug/Fugio/issues

Braeden: Good idea, I will put them up there ☺

**Comment by bigfug** [comment]
I've split out your request into individual issues so I can address them individually.
