### ISSUE TITLE
No plugins loaded on macOS

### ISSUE THREAD

**Issue by aalex** [bigfug/Fugio#55]
On macOS 10.14, using Fugio 3.0.1 (x86_64/x86_64), no plugins seem to be loaded.

See the attached screenshot of the Logger window for the messages when trying to open some examples. 
<img width="659" alt="capture d ecran le 2018-11-10 a 15 48 26" src="https://user-images.githubusercontent.com/293677/48305857-45496a00-e500-11e8-90d5-9ef703ff4a4b.png">

**Comment by Humbru** [comment]
I'm in MacOS 10.12.6 also using Fugio 3.0.1 (x86_64/x86_64) and got the same problem. No plug-ins and examples are loaded. A way around this is to 'show the package contents" open the MacOs folder and  open (double click) the fugio  program. Plug-ins and examples are loaded now but some nodes (e.g.. lua) don't work and crash the program. See attached logger info before it crashes.

Adding Universe Interface: "en0" "en0" "192.168.178.255" "A8:20:66:36:4D:BC"
Plugin Directory: "/Applications/Fugio-3.0.1-macOS/plugins"
"/Applications/Fugio-3.0.1-macOS/plugins/fugio-artoolkit.bundle/Contents/MacOS/fugio-artoolkit" : "Cannot load library /Applications/Fugio-3.0.1-macOS/plugins/fugio-artoolkit.bundle/Contents/MacOS/fugio-artoolkit: (dlopen(/Applications/Fugio-3.0.1-macOS/plugins/fugio-artoolkit.bundle/Contents/MacOS/fugio-artoolkit, 133): Library not loaded: @loader_path/../Frameworks/liblua.5.3.dylib\n  Referenced from: /Applications/Fugio-3.0.1-macOS/plugins/fugio-artoolkit.bundle/Contents/MacOS/fugio-artoolkit\n  Reason: image not found)"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-audio.bundle/Contents/MacOS/fugio-audio"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-colour.bundle/Contents/MacOS/fugio-colour"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-core.bundle/Contents/MacOS/fugio-core"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-dlib.bundle/Contents/MacOS/fugio-dlib"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-ffmpeg.bundle/Contents/MacOS/fugio-ffmpeg"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-fftw.bundle/Contents/MacOS/fugio-fftw"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-file.bundle/Contents/MacOS/fugio-file"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-firmata.bundle/Contents/MacOS/fugio-firmata"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-freeframe.bundle/Contents/MacOS/fugio-freeframe"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-geometry.bundle/Contents/MacOS/fugio-geometry"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-gui.bundle/Contents/MacOS/fugio-gui"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-image.bundle/Contents/MacOS/fugio-image"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-isf.bundle/Contents/MacOS/fugio-isf"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-kinect.bundle/Contents/MacOS/fugio-kinect"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-leapmotion.bundle/Contents/MacOS/fugio-leapmotion"
"/Applications/Fugio-3.0.1-macOS/plugins/fugio-lua.bundle/Contents/MacOS/fugio-lua" : "Cannot load library /Applications/Fugio-3.0.1-macOS/plugins/fugio-lua.bundle/Contents/MacOS/fugio-lua: (dlopen(/Applications/Fugio-3.0.1-macOS/plugins/fugio-lua.bundle/Contents/MacOS/fugio-lua, 133): Library not loaded: @loader_path/../Frameworks/liblua.5.3.dylib\n  Referenced from: /Applications/Fugio-3.0.1-macOS/plugins/fugio-lua.bundle/Contents/MacOS/fugio-lua\n  Reason: image not found)"
"/Applications/Fugio-3.0.1-macOS/plugins/fugio-luaqt.bundle/Contents/MacOS/fugio-luaqt" : "Cannot load library /Applications/Fugio-3.0.1-macOS/plugins/fugio-luaqt.bundle/Contents/MacOS/fugio-luaqt: (dlopen(/Applications/Fugio-3.0.1-macOS/plugins/fugio-luaqt.bundle/Contents/MacOS/fugio-luaqt, 133): Library not loaded: @loader_path/../Frameworks/liblua.5.3.dylib\n  Referenced from: /Applications/Fugio-3.0.1-macOS/plugins/fugio-luaqt.bundle/Contents/MacOS/fugio-luaqt\n  Reason: image not found)"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-math.bundle/Contents/MacOS/fugio-math"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-midi.bundle/Contents/MacOS/fugio-midi"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-ndi.bundle/Contents/MacOS/fugio-ndi"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-network.bundle/Contents/MacOS/fugio-network"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-oculusrift.bundle/Contents/MacOS/fugio-oculusrift"
"/Applications/Fugio-3.0.1-macOS/plugins/fugio-opencv.bundle/Contents/MacOS/fugio-opencv" : "Cannot load library /Applications/Fugio-3.0.1-macOS/plugins/fugio-opencv.bundle/Contents/MacOS/fugio-opencv: (dlopen(/Applications/Fugio-3.0.1-macOS/plugins/fugio-opencv.bundle/Contents/MacOS/fugio-opencv, 133): Library not loaded: @rpath/libopencv_flann.3.4.dylib\n  Referenced from: /Applications/Fugio-3.0.1-macOS/plugins/fugio-opencv.bundle/Contents/Frameworks/libopencv_features2d.3.4.dylib\n  Reason: image not found)"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-opengl.bundle/Contents/MacOS/fugio-opengl"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-osc.bundle/Contents/MacOS/fugio-osc"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-painter.bundle/Contents/MacOS/fugio-painter"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-portaudio.bundle/Contents/MacOS/fugio-portaudio"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-portmidi.bundle/Contents/MacOS/fugio-portmidi"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-raspberrypi.bundle/Contents/MacOS/fugio-raspberrypi"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-serial.bundle/Contents/MacOS/fugio-serial"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-spout.bundle/Contents/MacOS/fugio-spout"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-syphon.bundle/Contents/MacOS/fugio-syphon"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-text.bundle/Contents/MacOS/fugio-text"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-time.bundle/Contents/MacOS/fugio-time"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-videocapture.bundle/Contents/MacOS/fugio-videocapture"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-vst.bundle/Contents/MacOS/fugio-vst"
Loading plugin: "/Applications/Fugio-3.0.1-macOS/plugins/fugio-xinput.bundle/Contents/MacOS/fugio-xinput"
Initialising plugin AudioPlugin
Initialising plugin ColourPlugin
Initialising plugin CorePlugin
Initialising plugin DlibPlugin
Initialising plugin ffmpegPlugin
Initialising plugin FftwPlugin
Initialising plugin FilePlugin
Initialising plugin FirmataPlugin
Initialising plugin FreeframePlugin
Initialising plugin GeometryPlugin
Initialising plugin GuiPlugin
Initialising plugin ImagePlugin
Initialising plugin ISFPlugin
Initialising plugin KinectPlugin
Initialising plugin LeapMotionPlugin
Initialising plugin MathPlugin
Initialising plugin MidiPlugin
Initialising plugin NDIPlugin
Initialising plugin NetworkPlugin
Initialising plugin OculusRiftPlugin
Initialising plugin OpenGLPlugin
Initialising plugin OpenSoundControlPlugin
Initialising plugin PainterPlugin
Initialising plugin PortAudioPlugin
PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4
DefInp: 3 DefOut: 3
Core Audio "Built-in Microphone" 2 0
Core Audio "Built-in Input" 2 0
Core Audio "Built-in Output" 0 2
Core Audio "Scarlett 6i6 USB" 6 12
Core Audio "Adobe Encore DVD 6.0" 0 0
Core Audio "After Effects 11.0" 0 0
Core Audio "After Effects 11.0.4" 0 0
Core Audio "Premiere Elements 11.0" 0 0
Core Audio "Premiere Pro 6.0" 0 0
Initialising plugin PortMidiPlugin
0 "CoreMIDI" "IAC-besturingsbestand Bus 1" 1 0
1 "CoreMIDI" "Scarlett 6i6 USB" 1 0
2 "CoreMIDI" "IAC-besturingsbestand Bus 1" 0 1
3 "CoreMIDI" "Scarlett 6i6 USB" 0 1
Default Input: 0 Default Output: 2
Initialising plugin RaspberryPiPlugin
Initialising plugin SerialPlugin
Initialising plugin SpoutPlugin
Initialising plugin SyphonPlugin
Initialising plugin TextPlugin
Initialising plugin TimePlugin
Initialising plugin VideoCapturePlugin
Initialising plugin VSTPlugin
Initialising plugin XInputPlugin
Initialising plugin FreeframePlugin
Initialising plugin ISFPlugin
Initialising plugin MidiPlugin
Initialising plugin OpenGLPlugin
Initialising plugin SpoutPlugin
Initialising plugin FreeframePlugin
Initialising plugin ISFPlugin
Initialising plugin MidiPlugin
Initialising plugin MidiPlugin
Initialising plugin MidiPlugin (Last Chance)
"Plugins loaded: 34"
"Nodes registered: 298"

**Comment by kino-tech** [comment]
Same problem here
on first start up of the app the system comes up fine
But
IN THE CONSOLE:
Adding Universe Interface: "en0" "en0" "192.168.0.255" "6C:19:C0:E7:63:A8"
"Plugins loaded: 0"
"Nodes registered: 0"

MacOS 10.14.1

**Comment by rnkn** [comment]
This is fixed in the weekly build, 3.1.0

**Comment by kino-tech** [comment]
yay  -- thank you
