### ISSUE TITLE
Italian translation isn't loaded

### ISSUE THREAD

**Issue by MassiminoilTrace** [bigfug/Fugio#60]
Italian translated files are not listed in the .qrc file.
For example, the file "translations.qrc" in the project directory appears as
```
<RCC>
    <qresource prefix="/">
        <file>translations_de.qm</file>
        <file>translations_es.qm</file>
        <file>translations_fr.qm</file>
    </qresource>
</RCC>
```
If I manually add a line `<file>translations_it.qm</file>` to the file, it loads the translation of main interface only.
I don't know how to generate this line in all interested resource files, so I have to open this issue.
Thank you for your work.

I am using QT Creator on Fedora Linux 29

**Comment by MassiminoilTrace** [comment]
I also tried installing the weekly build from your site on Windows 10. Same issue on windows

**Comment by bigfug** [comment]
Thanks for that - hadn't started the final checks for 3.1.0 but it will be in the next weekly build
