### ISSUE TITLE
We’re removing the cask from the repo

### ISSUE THREAD

**Issue by vitorgalvao** [bigfug/Fugio#63]
Hello @bigfug,

Homebrew Cask (HBC) maintainer here.

Heads up, as you seem to mention HBC a few times in the code/wiki: [we’ll be removing the cask from the main repo](https://github.com/Homebrew/homebrew-cask/pull/59112), [for the following reasoning](https://github.com/Homebrew/homebrew-cask/pull/59097#issuecomment-464809195):

> Cask that is failing CI, has a ton of formula dependencies, and nobody uses (added 707 days ago, 2 downloads in the last 365, both in the last 90). Let’s remove it.

You might be the only one that uses the cask, or it might be that none of your users has analytics enabled. In the end, we’re removing the cask due to the maintenance burden. You may wish to consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) to allow your users to continue installing `fugio` via HBC.

We’re aiming to remove it on Sunday, Feb 24<sup>th</sup>, to give you time. If you need more time, please do let us know.

**Comment by bigfug** [comment]
Hi Victor,

That's fine to remove it.  People seem to install it via the main binary download anyway.

Thanks for letting me know.
