### ISSUE TITLE
Documentation links to wiki broken

### ISSUE THREAD

**Issue by donert** [bigfug/Fugio#78]
Links such as http://wiki.bigfug.com/view/Nodes:Add?utm_source=fugio&utm_medium=node-info
return error
Fatal error: Uncaught Error: Class 'FormatJson' not found in /homepages/21/d204069791/htdocs/wiki/w/includes/exception/MWExceptionHandler.php:624 Stack trace: #0 

Seems true for all wiki links

**Comment by donert** [comment]
As per email from Alex, the wiki has been deleted. _Some_ of the content is still visible at https://web.archive.org/web/20190801201437/http://wiki.bigfug.com/view/Main_Page

**Comment by bigfug** [comment]
All documentation will be moving to https://github.com/bigfug/Fugio/wiki
